version: '3.8'

services:
  proxy-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    restart: unless-stopped
    volumes:
      - ./proxy.crt:/app/proxy.crt
      - ./proxy.key:/app/proxy.key
